"""Draw the sediment decision chart on the "Sediment transport" setup page.

Writes sediment_decision_chart.dot and renders it to .svg (HTML) and .pdf
(LaTeX). The rendered files are committed, so building the docs does not
need Graphviz; only rerunning this does (``conda install graphviz``)::

    python make_sediment_decision_chart.py

Keep the questions and options in step with the numbered list under the
chart in sediment.rst.
"""
import shutil
import subprocess

ROWS = {
    'q1': ('1  What is the bed made of?', [
        ('Sand, gravel, or mud that moves as flocs',
         ["set_bed_material('noncohesive')",
          "entrainment='smith_mclean' (default),",
          "or 'de_leeuw' for sand rivers and deltas"]),
        ('Clay or silt that binds',
         ["set_bed_material('cohesive', tau_crit=...)",
          "tau_crit in Pa, ideally from a jet test"])]),
    'q2': ('2  How does it move?\nRouse number Z = w_s / (0.41 u*)', [
        ('Z above 2.5: bedload only', ["set_bedload('wong_parker_eq24')"]),
        ('Z from 0.8 to 2.5: both', ["set_bedload(...) as well"]),
        ('Z below 0.8: suspension', ["no bedload (the default)"])]),
    'q3': ('3  Is the suspension stratified?', [
        ('Yes, Z above about 0.1', ["set_deposition(near_bed='rouse')"]),
        ('No, well mixed', ["keep d* = 1 (the default)"])]),
    'q4': ('4  What sets the bed shear?', [
        ('Open channel or floodplain',
         ["the defaults: 'quadratic_drag'", "with the domain's Manning n"]),
        ('Vegetation', ["set_vegetation_drag(...,", "    sediment_shear='bed')"])]),
    'q5': ('5  How much of the bed can erode?', [
        ('A layer over rock, or a lining', ["set_erodible_base(depth=...)"]),
        ('Only part may scour', ["set_erodible_region(...)"]),
        ('Banks or holes that should slump', ["set_angle_of_repose(35.0)"])]),
    'q6': ('6  Several grain sizes, and\nthe bed sorts them?', [
        ('Yes: mud over sand, armouring',
         ["set_bed_composition(fractions,", "    active_layer=0.01)",
          "after set_erodible_base"])]),
    'q7': ('7  Is the bed much slower\nthan the flow?', [
        ('Days to years of bed change',
         ["set_sediment_parameters(", "    morphological_factor=M)"]),
        ('A fixed bed (analytic check)', ["bed_evolution=False"])]),
}


def esc(s):
    return s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def options_table(opts):
    cells = []
    for i, (cond, code) in enumerate(opts):
        rule = '' if i == len(opts) - 1 else ' SIDES="B" BORDER="1"'
        txt = '<B>%s</B>' % esc(cond)
        for c in code:
            txt += ('<BR ALIGN="LEFT"/><FONT FACE="Courier" POINT-SIZE="11">%s</FONT>'
                    % esc(c).replace(' ', '&#160;'))
        cells.append('<TR><TD ALIGN="LEFT" BALIGN="LEFT" CELLPADDING="4"%s>%s'
                     '<BR ALIGN="LEFT"/></TD></TR>' % (rule, txt))
    return ('<TABLE BORDER="1" COLOR="#9aa5b1" CELLBORDER="0" CELLSPACING="0" '
            'CELLPADDING="2" STYLE="ROUNDED">%s</TABLE>' % ''.join(cells))


def dot_source():
    out = ['// Sediment decision chart for the "Sediment transport" setup page.',
           '// Generated by make_sediment_decision_chart.py -- edit that, not this.',
           'digraph sediment_choices {',
           '  graph [rankdir=TB, nodesep=0.18, ranksep=0.35, fontname="Helvetica", '
           'bgcolor="transparent"];',
           '  node  [fontname="Helvetica", fontsize=12, shape=box, style="rounded,filled", '
           'penwidth=1, margin="0.12,0.06"];',
           '  edge  [color="#4a78c2", penwidth=1.4, arrowsize=0.7];',
           '  start [label="add_sediment_fraction(name, diameter)\\nfor each grain size", '
           'fillcolor="#f3f4f6", color="#7b8794"];',
           '  done  [label="print(domain.sediment_summary())\\nthen calibrate against data", '
           'fillcolor="#f3f4f6", color="#7b8794"];']
    for k, (q, opts) in ROWS.items():
        out.append('  %s [label="%s", fillcolor="#e8f0fb", color="#4a78c2", width=2.9];'
                   % (k, q.replace('\n', '\\n')))
        out.append('  %s_o [shape=plain, style="", label=<%s>];' % (k, options_table(opts)))
    keys = list(ROWS)
    out.append('  start -> %s;' % keys[0])
    out.append('  %s -> done;' % ' -> '.join(keys))
    for k in keys:
        out.append('  {rank=same; %s; %s_o;}' % (k, k))
        out.append('  %s -> %s_o [style=dashed, color="#9aa5b1", arrowhead=none, penwidth=1];'
                   % (k, k))
    out.append('}')
    return '\n'.join(out) + '\n'


if __name__ == '__main__':
    with open('sediment_decision_chart.dot', 'w') as f:
        f.write(dot_source())
    dot = shutil.which('dot')
    if dot is None:
        raise SystemExit('Graphviz "dot" not found; wrote the .dot only')
    # The cairo renderers draw the text as outlines, so the browser cannot
    # substitute a wider font than the one Graphviz measured the boxes with.
    for fmt in ('svg', 'pdf'):
        subprocess.run([dot, '-T%s:cairo' % fmt, 'sediment_decision_chart.dot',
                        '-o', 'sediment_decision_chart.' + fmt], check=True)
