"""Phase 4 acceptance test: LM15 Example 2, sand deposition in quiescent water.

Liu, Mohammadian, Kurganov & Infante Sedano (2015), JCP 300, 202-218, Example 2,
described there as "designed to verify that the added source terms will not
affect the well-balanced property in quiescent water with uniform sediment
deposition".

That is exactly the question spec 9.5 defers: a fixed-bed well-balanced scheme
does not stay well-balanced once z is time-varying. Here the bed AGGRADES under
a depositing sediment plume while the free surface must stay flat and the
velocity exactly zero. It is cheap, needs no field data, and fails loudly.

LM15's setup, their section 5:
    domain [0,2] x [0,1], 3628 triangles
    eta = 1, u = v = Z = 0
    c(x,y,0) = 0.7 exp(-5(x-0.9)^2 - 50(y-0.5)^2)
    g = 9.8, porosity p = 0.28, d = 0.01, rho_s = 2400, rho_f = 1000

Deviations, both deliberate:
  * Reflective rather than zero-order-extrapolation boundaries. A lake at rest
    is preserved exactly by reflection, so boundary noise cannot be mistaken for
    a well-balancedness failure. This makes the test stricter, not weaker.
  * c_max and c_pack are raised for this test only. LM15's peak c = 0.7 is above
    both our defaults ([L-2] 0.30, [L-4] 0.65); clipping it would change the
    experiment. This test is about well-balancedness, not the limiters.

UNTIL [G-4] IS IMPLEMENTED THIS FAILS AT CHECK B1 -- the bed never moves. That
is the point: the acceptance criterion exists before the code that must satisfy
it.
"""
import numpy as np
import anuga
from anuga import Reflective_boundary, rectangular_cross_domain

_fail = [0]
LAMBDA = 0.28
D_G = 0.01
RHO_S, RHO_W = 2400.0, 1000.0
T_END = 20.0


def check(label, ok, detail=''):
    print('  [%s] %s' % ('PASS' if ok else 'FAIL', label))
    if detail:
        print('         ' + detail)
    if not ok:
        _fail[0] += 1
    return ok


def build(mode=1):
    d = rectangular_cross_domain(42, 21, len1=2.0, len2=1.0)
    d.set_flow_algorithm('DE0')
    d.set_low_froude(0)
    d.store = False
    d.set_quantity('elevation', 0.0)
    d.set_quantity('stage', 1.0)
    d.set_quantity('xmomentum', 0.0)
    d.set_quantity('ymomentum', 0.0)
    d.set_quantity('friction', 0.0)
    d.set_boundary({t: Reflective_boundary(d) for t in d.get_boundary_tags()})
    d.sediment_c_max = 0.80
    d.sediment_c_pack = 0.80
    d.sediment_porosity = LAMBDA
    if mode != 1:
        d.set_multiprocessor_mode(mode)
    x, y = d.centroid_coordinates[:, 0], d.centroid_coordinates[:, 1]
    c0 = 0.7 * np.exp(-5.0 * (x - 0.9)**2 - 50.0 * (y - 0.5)**2)
    d.add_sediment_class('sand', diameter=D_G, rho_s=RHO_S, rho_w=RHO_W,
                         tau_c_star=0.0,
                         initial_concentration=c0)
    return d, c0   # add_sediment_class registers the operator


print(__doc__)

d, c0 = build()
areas = d.areas
z0 = d.quantities['elevation'].centroid_values.copy()
w0 = d.quantities['stage'].centroid_values.copy()
m0 = float((d.tracer_conserved_values[0] * areas).sum())
print('  v_s = %.4e m/s   initial suspended mass = %.6e   peak c = %.3f'
      % (d.sediment_settling_velocity[0], m0, c0.max()))

d.evolve_to_end(finaltime=T_END)

z1 = d.quantities['elevation'].centroid_values
w1 = d.quantities['stage'].centroid_values
h1 = np.maximum(w1 - z1, 0.0)
u = d.quantities['xmomentum'].centroid_values
v = d.quantities['ymomentum'].centroid_values
m1 = float((d.tracer_conserved_values[0] * areas).sum())
dz = z1 - z0

check('A1. free surface stays flat: stage is unchanged everywhere',
      np.allclose(w1, w0, rtol=0, atol=1e-10),
      'max|stage - 1| = %.3e' % np.abs(w1 - w0).max())
check('A2. no spurious momentum is generated by the moving bed',
      np.abs(u).max() < 1e-10 and np.abs(v).max() < 1e-10,
      'max|xmom| = %.3e   max|ymom| = %.3e' % (np.abs(u).max(), np.abs(v).max()))

check('B1. the bed rises where the sediment plume was',
      dz.max() > 0.0,
      'max dz = %.6e; LM15 Fig 5 shows a bed mound there' % dz.max())
# Every cell should have deposited exactly its OWN sediment and no more: the
# water is at rest, so there is no lateral transport and dz = c0 h0/(1-lambda)
# cell by cell. Much stronger than "the bed did not move where c was small" --
# the Gaussian is never exactly zero, so that weaker form is satisfied by any
# roughly-right answer.
m0_cell = c0 * (w0 - z0)
m1_cell = d.tracer_conserved_values[0]
check('B2. per-cell budget is exact: (1-lambda) dz = m_lost in that cell',
      np.allclose((1.0 - LAMBDA) * dz, m0_cell - m1_cell, rtol=0, atol=1e-12),
      'max|(1-lambda) dz - dm| = %.3e   (no lateral transport: the water is at '
      'rest, so each cell keeps its own sediment)'
      % np.abs((1.0 - LAMBDA) * dz - (m0_cell - m1_cell)).max())
# and it should be CLOSE to complete deposition, but not exactly: deposition
# decays exponentially, so a small residue is still in suspension at t = 20.
dz_full = m0_cell / (1.0 - LAMBDA)
check('B2b. and is within 1e-4 of full deposition at t = 20 s',
      np.abs(dz - dz_full).max() < 1e-4 * dz_full.max(),
      'peak dz %.6f vs full %.6f; residual suspended fraction %.2e'
      % (dz.max(), dz_full.max(), m1_cell.sum() / max(m0_cell.sum(), 1e-30)))
com = float((d.centroid_coordinates[:, 0] * dz).sum() / max(dz.sum(), 1e-30))
check('B3. the bed rise is co-located with the initial plume',
      abs(com - 0.9) < 0.15,
      'centre of mass of dz at x = %.3f (plume centred at x = 0.9)' % com)

bed_gain = float(((1.0 - LAMBDA) * dz * areas).sum())
lost = m0 - m1
check('C1. sediment lost from suspension equals sediment gained by the bed',
      abs(bed_gain - lost) <= 1e-8 * max(abs(lost), 1.0),
      'suspended loss %.10e   bed gain (1-lambda)*dz %.10e   diff %.3e'
      % (lost, bed_gain, bed_gain - lost))
check('C2. water depth falls by exactly the bed rise (stage held)',
      np.allclose(h1, (w0 - z0) - dz, rtol=0, atol=1e-12),
      'max|h - (h0 - dz)| = %.3e' % np.abs(h1 - ((w0 - z0) - dz)).max())

res = {}
for mode in (1, 2):
    dm, _ = build(mode=mode)
    ok = (mode == 1) or getattr(dm, 'multiprocessor_mode', None) == 2
    dm.evolve_to_end(finaltime=T_END)
    res[mode] = (dm.quantities['elevation'].centroid_values.copy(), ok)
check('D1. mode 2 engaged', res[2][1])
check('D2. mode 1 and mode 2 give the same bed',
      np.allclose(res[1][0], res[2][0], rtol=0, atol=1e-8),
      'max|dz diff| = %.3e' % np.abs(res[1][0] - res[2][0]).max())

n = 2 + 4 + 2 + 2
print('\n  %d/%d passed' % (n - _fail[0], n))
raise SystemExit(1 if _fail[0] else 0)
