
python_sources = [
  'test_boyd_box_operator.py',
  'test_boyd_pipe_operator.py',
  'test_inlet_operator.py',
  'test_inlet_tracers.py',
  'test_structure_tracers.py',
  'test_internal_boundary_functions.py',
  'test_internal_boundary_operator.py',
  'test_riverwall_structure.py',
  'test_structure_inlet_region_consistency.py',
  'test_structure_operator.py',
  'test_weir_orifice_trapezoid_operator.py',
]

py3.install_sources(
  python_sources,
  subdir: 'anuga/structures/tests'
)

subdir('data')