#
# earthquake_tsunami function
#
#import okada
"""This function returns a callable object representing an initial water
   displacement generated by a submarine earthqauke.

Using input parameters:

Required
 length  along-stike length of rupture area
 width   down-dip width of rupture area
 strike  azimuth (degrees, measured from north) of fault axis
 dip     angle of fault dip in degrees w.r.t. horizontal
 depth   depth to base of rupture area

Optional
 x0      x origin (0)
 y0      y origin (0)
 slip    metres of fault slip (1)
 rake    angle of slip (w.r.t. horizontal) in fault plane (90 degrees)

The returned object is a callable okada function that represents
the initial water displacement generated by a submarine earthuake.

"""
def earthquake_tsunami(length, width, strike, depth, \
                       dip, x0=0.0, y0=0.0, slip=1.0, rake=90.,\
                       domain=None, verbose=False):

    from math import sin, radians

    if domain is not None:
        xllcorner = domain.geo_reference.get_xllcorner()
        yllcorner = domain.geo_reference.get_yllcorner()
        x0 = x0 - xllcorner  # fault origin (relative)
        y0 = y0 - yllcorner

    #a few temporary print statements
    if verbose is True:
        print('\nThe Earthquake ...')
        print('\tLength: ', length)
        print('\tDepth: ', depth)
        print('\tStrike: ', strike)
        print('\tWidth: ', width)
        print('\tDip: ', dip)
        print('\tSlip: ', slip)
        print('\tx0: ', x0)
        print('\ty0: ', y0)

    # warning test
    test = width*1000.0*sin(radians(dip)) - depth

    if verbose is True:
        if test > 0.0:
            print('Earthquake source not located below seafloor')
            print('Please check depth')

    return Okada_func(length=length, width=width, dip=dip, \
                      x0=x0, y0=y0, strike=strike, depth=depth, \
                      slip=slip, rake=rake, test=test)


#
# Okada class
#

"""This is a callable class representing the initial water displacment
   generated by an earthquake.

Using input parameters:

Required
 length  along-stike length of rupture area
 width   down-dip width of rupture area
 strike  azimuth (degrees, measured from north) of fault axis
 dip     angle of fault dip in degrees w.r.t. horizontal
 depth   depth to base of rupture area

Optional
 x0      x origin (0)
 y0      y origin (0)
 slip    metres of fault slip (1)
 rake    angle of slip (w.r.t. horizontal) in fault plane (90 degrees)

"""

class Okada_func:

    def __init__(self, length, width, dip, x0, y0, strike, \
                 depth, slip, rake, test):
        self.dip = dip
        self.length = length
        self.width = width
        self.x0 = x0
        self.y0 = y0
        self.strike = strike
        self.depth = depth
        self.slip = slip
        self.rake = rake
        self.test = test


    def __call__(self, x, y):
        """Make Okada_func a callable object.

        If called as a function, this object returns z values representing
        the initial 3D distribution of water heights at the points (x,y)
        produced by a submarine mass failure.
        """

        raise NotImplementedError(
            "eqf.Okada_func is not callable: it depends on a compiled Fortran 'okada' "
            "extension that ANUGA no longer builds (only the okada.f source remains). "
            "The body also called okada() while importing okadatest, so it could not "
            "have worked even with the extension present. "
            "Use anuga.tsunami_source.tsunami_okada.Okada_func instead — a pure-Python "
            "implementation that is built, tested and maintained.")


