python_sources = [
    '__init__.py',
    'test_parse_input_data_toml.py',
    'test_read_boundary_tags.py',
    'test_setup_boundary_conditions.py',
    'test_setup_rainfall.py',
    'test_scenario_integration.py',
    'test_run_toml_end_to_end.py',
]

py3.install_sources(
    python_sources,
    subdir: 'anuga/scenario/tests'
)
