
python_sources = [
  '__init__.py',
  'run_parallel_collaborative_domain.py',
  'run_parallel_distribute_domain.py',
  'run_parallel_distribute_mesh.py',
  'run_parallel_riverwall.py',
  'run_parallel_shallow_domain.py',
  'run_parallel_sw_flow.py',
  'skip_parallel_boyd_box_op_apron.py',
  'skip_parallel_boyd_box_operator.py',
  'skip_parallel_boyd_pipe_operator.py',
  'skip_parallel_distribute_mesh.py',
  'test_partitioning.py',
  'test_reorder_domain.py',
  'test_distribute_mesh.py',
  'test_distribute_basic_mesh.py',
  'test_failure.py',
  'test_parallel_boyd_box_operator_consistency.py',
  'test_parallel_boyd_box_operator.py',
  'test_parallel_collaborative_domain.py',
  'test_parallel_distribute_domain.py',
  'test_parallel_dist_settings.py',
  'test_parallel_file_boundary.py',
  'test_parallel_frac_op.py',
  'test_parallel_inlet_fsvi.py',
  'test_parallel_inlet_operator.py',
  'test_parallel_inlet_operator_with_region.py',
  'test_parallel_riverwall.py',
  'test_parallel_shallow_domain.py',
  'test_parallel_sw_flow_de0.py',
  'test_parallel_sw_flow_de1.py',
  'test_parallel_sw_flow_de_ader2.py',
  'test_parallel_sw_flow_de2.py',
  'test_parallel_sw_flow_low_froude_0.py',
  'test_parallel_sw_flow_low_froude_1.py',
  'test_parallel_sw_flow.py',
  'test_parallel_sw_flow_gpu_de0.py',
  'test_parallel_sw_flow_gpu_de1.py',
  'test_parallel_sw_flow_gpu_de2.py',
  'test_parallel_sw_flow_gpu_de_ader2.py',
  'test_parallel_meshes.py',
  'test_sequential_dist_sw_flow.py',
  'run_parallel_kv_operator.py',
  'test_parallel_kv_operator.py',
  'run_parallel_kv_unit_tests.py',
  'test_parallel_kv_unit_tests.py',
  'run_parallel_load_balance.py',
  'test_load_balance_statistics.py',
  'test_sequential_mesh_io.py',
  'test_mesh_refinement.py',
]

py3.install_sources(
  python_sources,
  subdir: 'anuga/parallel/tests'
)
